language: python

sudo: false

install:
    pip install tox

script: tox

matrix:
  include:
    - env: TOXENV=py27
      python: 2.7
    - env: TOXENV=py33
      python: 3.3
    - env: TOXENV=py34
      python: 3.4
    - env: TOXENV=py35
      python: 3.5
    - env: TOXENV=pypy
      python: pypy
    - env: TOXENV=pypy3
      python: pypy3
    - env: TOXENV=py27-flake8
      python: 2.7
    - env: TOXENV=py34-flake8
      python: 3.4
