language: python

sudo: false

install:
    pip install tox

script: tox

env:
  matrix:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=py35
  - TOXENV=pypy
  - TOXENV=pypy3
  - TOXENV=py27-flake8
  - TOXENV=py34-flake8
